package main

/*
This is an autogenerated file by autobindings
*/

import (
	"github.com/mholt/binding"
)

func (m *MailgunSettings) FieldMap() binding.FieldMap {
	return binding.FieldMap{
		&m.Domain:     "mgdomain",
		&m.PrivateKey: "mgprikey",
	}
}
