package main

import (
	//"log"
	"net/http"
)

/*
This is an autogenerated file by autobindings
*/

import (
	"github.com/mholt/binding"
)

func (u *User) FieldMap() binding.FieldMap {
	return binding.FieldMap{
		&u.Avatar:   "avatar",
		&u.Email:    "email",
		&u.ID:       "id",
		&u.Name:     "name",
		&u.Password: "password",
		&u.Posts:    "posts",
	}
}

func (u *User) Validate(req *http.Request, errs binding.Errors) binding.Errors {
	//log.Println("bindingvalidate: ", u)
    return errs
}
